users/alice/home.nix

Topgrade is upgrading from local instead of remote, and throws an error when it tries to upgrade nix. Disabling these checks.

Disable system,nix updates from Topgrade

---

systems/palatine-hill/configuration.nix
users/alice/home.nix

Adjusts settings so topgrade will work on the system as configured, unfortunately requires disabling podman as topgrade will always prefer podman over docker

Disable podman, fix topgrade config

---

flake.nix

Run `nix-develop` to test these changes yourself. 
- Adds a hook that will always check if your remote hooks are up to date (ours are all local currently but it leaves the option open).
- Modifies `nixpkgs-fmt` hook to be check only and renamed to `nixpkgs-fmt check`. From now on if this fails the committer will need to run `nix fmt`.

Add pre-commit-update hook, make nixpkgs-fmt check only

---

systems/palatine-hill/configuration.nix

Typo in hydra gcroots means that all the nix derivations are getting stored on the SSD instead of ZFS.

Fix hydra directory

---

systems/configuration.nix

Adds automatic hardlink optimization once every 24 hours, as well as adding a setting which will force nix to garbage collect up to 10gb of stuff whenever less than one gb is available to /nix

space optimizations

---

users/alice/secrets.yaml

jeeves is having an issue pulling updates as the age key changed.. i checked the nix store path on palatine-hill and its pointing at my secrets file which apparently needed an `sops updatekeys`.
I think the main reason `nixos-rebuild` was failing was due to the flake config changes (either cache or substitutors i'm not sure), which is expected and normally remediated when the next manually invoked upgrade is triggered. I ran a manual update off the main branch and it seems to be working but this sops fix should close out any other potential failures.
affected nix store path:
/nix/store/fjjxfa1671g9rxnh9wih2p702pgwrqna-secrets.yaml
jeeves updates:
updatekeys:

update alice's sops keys, as age key for jeeves changed

---

flake.lock
flake.nix
users/alice/systems/artemision/configuration.nix

xz rebuild requires bootstrapping the toolchain, and rebuilds something stupid like 5,000 packages in total. given the sheer scale, apparently that's around 10 days worth of compute on the nixpkgs hydra cluster and the reverted package won't be available in nixos-unstable for probably 6-8 more days. Its likely that nixos isn't directly impacted as the specific payload was looking for debian and rpm specific files and variables (and relies on a patch which nixos didn't include), but out of an abundance of caution, we should probably flip over to nixos-unstable-small.
since nixos-unstable-small is geared towards servers and has a reduced closure size, there is a chance we're gonna be building GUI apps more often. The increased build cost on main can be redirected to the hydra instance we …

switch to nixos-unstable-small, which already finished the xz revert

---

.github/workflows/flake-update.yml

Since we have Hydra set up now for the flake update branch, this will let us see if we can upgrade safely, as well as pushing more artifacts into the cache.

does flake updates every day at noon

---

users/alice/systems/artemision/fonts.nix

restricts the font list to a subset of nerdfonts

override nerdfonts for artemision

---

systems/artemision/wifi.nix

artemision is currently having some really weird issues whenever its using the local unbound DNS, so this is demoting the local DNS and adding some public networks

wifi fixes

---

lib/systems.nix
modules/base.nix
systems/artemision/default.nix
systems/rhapsody-in-green/default.nix
users/alice/home.nix
users/alice/non-server.nix

Depends on #188 being merged
- passes a new `machineConfig` option to home-manager, which currently only contains the `server` boolean attribute, although can be expanded to support any attribute which is passed to the system via a change in `modules/base.nix` and `lib/systems.nix`.
- Sets up artemision and rhapsody-in-green as explicity `server = false`
- Moves some of the artemision config to the new `users/alice/non-server.nix`, which is imported to the primary config using `lib.optionals` and `machineConfig.server`

Home-manager server/non-server config option

---

users/default.nix

as per the debian man pages, there is a default option for `plocate` [-l, --require-visibility FLAG](https://manpages.debian.org/unstable/plocate/updatedb.plocate.8.en.html#l). Basically, the user only gets access to the plocate database if it has the `plocate` group and then the files are only visible if the user has access to all parent folders. See an example below with a test file.
folder creation (owned by root/root, 755 perms)
initial plocate results, file is visible as parent folder `plocatetestfolder/` has execute perms
`plocatetestfolder/` is visible as `nix-dotfiles` folder is visible, but `plocatetestfolder/plocatetestfile` isn't visible as the exec permission isn't set on the parent folder

plocate per-user file visibility

---

modules/plocate.nix

Fixes this warning:
`trace: warning: mlocate and plocate do not support the services.locate.localuser option. updatedb will run as root. Silence this warning by setting services.locate.localuser = null.`

fixes localuser warning due to plocate incompatibility

---

flake.lock
flake.nix
hydra/jobs.nix
lib/systems.nix
modules/generators.nix
modules/openssh.nix
systems/artemision/configuration.nix
systems/artemision/hardware.nix
systems/jeeves-jr/hardware.nix
systems/jeeves/hardware.nix
systems/palatine-hill/configuration.nix
systems/palatine-hill/hardware.nix
systems/rhapsody-in-green/hardware.nix

Adds `iso`, `install-iso`, and `qcow` generation for all machines via `nix build .#images.<format>.<hostname>`, and fixes (most of) the issues that were blocking image generation except for the one error below. 
I **very** briefly added this to Hydra, but the act of fixing an issue and pushing again like 2-4 times has caused the nix-store to explode and atticd to run out of memory. So yeah we're doing this one by request only.
Note: the `images.<format>` output is very much a convenience function. Any format can be build using the same logic as `lib.rad-dev.getImages` which is to say `nix build .#nixosConfigurations.<system>.config.formats.<format>` should do the same thing for any format available in [nixos-generators](https://github.com/nix-community/nixos-generators).
```
in job …
```

Image generation

---

flake.lock
flake.nix
modules/nix.nix

until palatine-hill is migrated to a location with gigabit upload, switch to `unstable` from `unstable-small`

swap to 24.05 for stable and from unstable-small to unstable

---

flake.nix

Removes `cache.alicehuston.xyz` from the flake (meaning only the faster downloads via attic will be done). This means that there's more stuff that the users are going to have to build from source, but the downloads are going to be significantly smaller.

remove cache.alicehuston.xyz

---

users/alice/non-server.nix

user config change only, removes pynose due to the below license violation
```shell       
error: pynose was removed, because it violates the license of nose, by redistributing modified LGPL code under MIT.
```

remove pynose from user config

---

systems/artemision/programs.nix

Until the wxpython compat PR is merged (nixpkgs PR 326142), disabling playonlinux so we can update finally hopefully
Proof that the update builds:

temporarily remove playonlinux from artemision

---

flake.nix
hydra/jobs.nix
hydra/jobsets.nix
hydra/spec.json
systems/palatine-hill/hydra.nix

This allows Hydra checks to report back to GitHub, and adds aggregate checks so the checks have a consistent schema for enabling check verification for PRs.
Part 2 of this will include disabling the nix-flake-check and formatting GitHub action.

Add aggregate checks, add Hydra feedback to GitHub

---

.gitignore
docs/CONTRIBUTING.md
shell.nix

Adds the ability to disable pre-commit-hooks by running `touch .noprecommit`, as well as updating the relevant docs

allow temporarily disabling pre-commit hooks

---

flake.lock
flake.nix
systems/palatine-hill/networking.nix

A staging PR for the next flake update
EDIT: bundling flake update in here as there are breaking changes which are dependent on the flake update (particularly pertaining to systemd). Can't update without these changes and cant make these changes without these updates.

Update `flake.lock` and make breaking systemd-networkd changes

---

systems/artemision/programs.nix
users/richie/home/gui/default.nix

removes cinnamon namespace from packages, as per recent nix warning.
